### ISSUE TITLE
Pod dependency changes can break libraries that use Kaocha as a sub-dependency

### ISSUE THREAD

**Issue by jffry** [lambdaisland/kaocha-boot#2]
## Overview

This applies to the most recent release, [kaocha-boot v0.0-14](https://github.com/lambdaisland/kaocha-boot/releases/tag/v0.0-14)

My problem stems from the fact that `kaocha.boot-task/make-kaocha-pod` will conj a specific, pretty old version of `[lambdaisland/kaocha "0.0-337"]` into the `:dependencies` of the Boot pod where it runs things, as seen in https://github.com/lambdaisland/kaocha-boot/blob/v0.0-14/src/kaocha/boot_task.clj#L9-L13

In some situations, described below, the addition of this top-level dependency to the pod changes which version of `kaocha` is being used, which can break other `kaocha` plugins (like `kaocha-cljs`) which depend on newer releases of `kaocha` than what `kaocha-boot` provides.

## Potential Solution

Unless I'm missing something about dependency management and boot pods, I believe `kaocha.boot-task/make-kaocha-pod` could be simplified to just `(pod/make-pod (boot/get-env))`.

`kaocha-boot` seems to already depend upon `kaocha` in its [pom.xml](https://github.com/lambdaisland/kaocha-boot/blob/v0.0-14/pom.xml#L33-L44), which means that it will be present in the pod.

If that's not an option, perhaps the `kaocha` task could provide a simple way for consumers to specify what extra dependencies are added into the pod?

## Detailed Explanation

The situation I'm in is that I have a private-to-my-company library that's a dependency across many of our repos, which provides a standardized set of Boot tasks.

Simplified to omit a lot of sub-sub dependencies, each repo's unresolved dependency tree looks like:

```
[my-company/some-project]
└── [my-company/private-boot-lib "1.0.0"]
    ├── [lambdaisland/kaocha "0.0-573"]
    ├── [lambdaisland/kaocha-boot "0.0-14"]
    │   └── [lambdaisland/kaocha "0.0-340"]
    └── [lambdaisland/kaocha-cljs "0.0-68"]
        └── [lambdaisland/kaocha "0.0-541"]
```

Presented with this single top level dependency, Boot will choose `[lambdaisland/kaocha "0.0-573"]` (I believe because it is the highest in the tree and has no conflicting peers at the same level in the tree)

However, when `kaocha-boot` adds the top-level dependency to its pod, the pod's dependencies are like:

```
[my-company/some-project >> kaocha.boot-task/make-kaocha-pod]
├── [my-company/private-boot-lib "1.0.0"]
│   ├── [lambdaisland/kaocha "0.0-573"]
│   ├── [lambdaisland/kaocha-boot "0.0-14"]
│   │   └── [lambdaisland/kaocha "0.0-340"]
│   └── [lambdaisland/kaocha-cljs "0.0-68"]
│       └── [lambdaisland/kaocha "0.0-541"]
└── [lambdaisland/kaocha "0.0-340"] ;injected
```

Boot will now resolve and use `[lambdaisland/kaocha "0.0-340"]`, as it is at the top level, and top-level deps override sub-dependencies.

Most of the Kaocha docs assume you're consuming it directly and would have it as a top-level dep; I can simulate that by including Kaocha alongside our boot lib:

```
[my-company/some-project >> kaocha.boot-task/make-kaocha-pod]
├── [lambdaisland/kaocha "0.0-573"]
├── [my-company/private-boot-lib "1.0.0"]
│   ├── [lambdaisland/kaocha-boot "0.0-14"]
│   │   └── [lambdaisland/kaocha "0.0-340"]
│   └── [lambdaisland/kaocha-cljs "0.0-68"]
│       └── [lambdaisland/kaocha "0.0-541"]
└── [lambdaisland/kaocha "0.0-340"] ;injected
```

Which would cause Boot to use `[lambdaisland/kaocha "0.0-573"]` as it is first in the order amongst conflicting top-level dependencies.

While we can adopt this solution temporarily, it may be better if `kaocha-boot` were less aggressive about adding a specific version into the pod.

## Simple Reproduction

Since `[lambdaisland/kaocha-cljs "0.0-68"]` depends on a newer version of `lambdaisland/kaocha` than `[lambdaisland/kaocha-boot "0.0-14"]`, we can reproduce this situation in a simple Boot project like so.

Given a `build.boot`:

```clojure
(set-env!
  :dependencies
  '[[lambdaisland/kaocha-boot "0.0-14"]
    [lambdaisland/kaocha-cljs "0.0-68"]])

(require '[kaocha.boot-task :refer [kaocha]])
```

and a `tests.edn`:

```clojure
#kaocha/v1
{:tests
  [{:id :unit-cljs
    :type :kaocha.type/cljs}]}
```

then `boot kaocha` should run without error.  If you try this, you will instead see an exception: `java.lang.RuntimeException: Unable to resolve symbol: symbol in this context`, the root cause of which is that `kaocha-boot` is forcing the use of an older version of `kaocha` that does not contain the reimplementaion of `symbol` that `kaocha-cljs` relies upon.

**Comment by plexus** [comment]
Hi @jffry , thanks for researching this in depth. Seems like you have a good understanding of what's happening. I'm all for lettingFeel free to make a pr with the changes you see fit and I'll put out a new release ASAP. if you do please do also update the CHANGELOG.
Thanks a lot!
